### ISSUE TITLE
need to build the apk for "armeabi-v7a",  there is error:   no find libkantv-core.so 

### ISSUE THREAD

**Issue by TaiXu2022** [zhouwg/kantv#103]
Dear zhou
thanks for your shared project, which is perfect 
I need to build the APP for armeabi-v7a,  after set the NDK ,  
happen the error:    ninja: error: 'C:/Users/windd/AndroidStudioProjects/kantv-master/cdeosplayer/kantv/src/main/jniLibs/armeabi-v7a/libkantv-core.so', needed by 'C:/Users/windd/AndroidStudioProjects/kantv-master/cdeosplayer/kantv/build/intermediates/cxx/Debug/4s5h6o55/obj/armeabi-v7a/libwhispercpp.so', missing and no known rule to make it

would you please upload the libkantv-core.so file for  armeabi-v7a,

thanks a lot

**Comment by zhouwg** [comment]
sorry to replay too late, I just see it.

(1) modify this file manually to generate libggml-jni.so( original libwhispercpp.so, the codes had been refactored according to new software architecture)

![kantv-android-arch](https://github.com/zhouwg/kantv/assets/6889919/ba5d10ed-a5c7-461c-8b55-b259a8f8420b)
 
https://github.com/zhouwg/kantv/blob/master/cdeosplayer/kantv/build.gradle#L20

(2) I don’t have an arm32 phone or device at my side, so I can’t provide the arm32 version of libkantv-core.so&libkantv-ffmpeg.so

**Comment by zhouwg** [comment]
As you do not require further assistance, I will close this opening issue. thanks.

**Comment by zhouwg** [comment]
Hi,

I'm so sorry that this issue is fixed finally today(04-07-2024, April 07, 2024) after sanity check with a NEW clone in a NEW directory.

Thanks for your issue report again.

Best wishes
