### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by wenwenwenzq** [zhouwg/kantv#17]
my build os Ubuntu20.0 ，all step i finished /build-all-native-libs.sh init can be executed successfully, but when it reaches the last step of ./build-all-native-libs.sh build, it error build libconv failed and ./configure not such file or directory found is displayed

**Comment by zhouwg** [comment]
> my build os Ubuntu20.0 ，all step i finished /build-all-native-libs.sh init can be executed successfully, but when it reaches the last step of ./build-all-native-libs.sh build, it error build libconv failed and ./configure not such file or directory found is displayed

pls refer to #1  ,  so we could fix the issue, thanks

**Comment by wenwenwenzq** [comment]
Host Operating System & Version：
Ubuntu 20

Kernel Version (Linux Only)：
4.14.13

Branch:
dev-baseon-latest-k0.8.8

Android Studio Version	
4.2.1

NDK Version	
r14b

Language	
C

Section
build

Issue Description
<Describe your issue / question / feature request / etc..>

fully log is welcomed

steps to reproduce issue is welcomed

fudev-baseon-lat… ll sequence of commands used is welcomed

**Comment by zhouwg** [comment]
sanity check in a stand-alone dev-envs  successfully according to 

https://github.com/zhouwg/kantv/blob/kantv/README.md
