### ISSUE TITLE
有没有关于此项目的微信交流群

### ISSUE THREAD

**Issue by zhuipiaochen** [zhouwg/kantv#226]
你好有没有关于此项目的微信交流群

**Comment by zhouwg** [comment]
> 你好有没有关于此项目的微信交流群

您好，目前没有。对项目感兴趣的，可以提交issue report或者code PR.

**Comment by zhuipiaochen** [comment]
大牛，你接下来准备做onnxruntime+qnn的后端支持？

**Comment by zhouwg** [comment]
> 大牛，你接下来准备做onnxruntime+qnn的后端支持？
1.😂 AI初学者
2.onnxruntime的QNN后端貌似已经有了：https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/core/providers/qnn

不过这里的方法不会被使用，原因是封装的太利害了。
