### ISSUE TITLE
请问本项目当前支持stable diffusion吗

### ISSUE THREAD

**Issue by zhuipiaochen** [zhouwg/kantv#232]

**Comment by zhouwg** [comment]
抱歉刚刚看到。

做了[初步的集成](https://github.com/zhouwg/kantv/tree/master/core/ggml/stablediffusioncpp)，代码可以编译通过。但是在小米14上运行有问题。

**Comment by zhouwg** [comment]
抱歉刚刚看到。

做了[初步的集成](https://github.com/zhouwg/kantv/tree/master/core/ggml/stablediffusioncpp)，代码可以编译通过。但是在小米14上运行有问题。

**Comment by zhouwg** [comment]
抱歉刚刚看到。

做了[初步的集成](https://github.com/zhouwg/kantv/tree/master/core/ggml/stablediffusioncpp)，代码可以编译通过。但是在小米14上运行有问题。

**Comment by zhouwg** [comment]
抱歉刚刚看到。

做了stablediffusion.cpp的[初步集成](https://github.com/zhouwg/kantv/tree/master/core/ggml/stablediffusioncpp)，代码可以编译通过。但是在小米14上运行有问题。原因是stablediffusion.cpp用到的ggml库与上游llama.cpp的ggml库有差异。

**Comment by zhouwg** [comment]
I'd like to close this opening issue accordingly and you can re-open it as your need in the future.thanks for your understanding.

**Comment by zhuipiaochen** [comment]
大牛 后续有兴趣一起做些项目吗

**Comment by zhouwg** [comment]
不是啥大牛，只是一个“技术不错（某国产头部手机大厂核心子系统架构师之语）”但因受限于文科生教育背景对硬核AI科技几乎一无所知的独立程序员。

真正的大牛在这里：

https://github.com/leejet/stable-diffusion.cpp


还有这位,国产推理框架的作者（强烈建议国内程序员给ncnn点赞，让星标冲过60+k，貌似国内唯一能拿得出手/能打的开源端侧推理框架了：

https://github.com/nihui/
