### ISSUE TITLE
How to implement a single whispercpp with qnn on Qualcomm SoC?

### ISSUE THREAD

**Issue by Weisonorz** [zhouwg/kantv#233]
Thanks for your work. I am new on using Qualcomm SoC systems. Just curious how can we implement whisper or llama cpp separately from this project?

**Comment by zhouwg** [comment]
I don't know what's the meaning you said.

**Comment by zhouwg** [comment]
I'd like to close this opening issue accordingly. of course, you can re-open it in the future as your need.thanks for your understanding.
