### ISSUE TITLE
mac 编译 Android 不了 求全套编译好的

### ISSUE THREAD

**Issue by 360060316** [zhouwg/kantv#55]
mac 编译 Android 不了 求全套编译好的

**Comment by 360060316** [comment]
作者请问mac怎么编译 Android 啊

**Comment by zhouwg** [comment]
> 作者请问mac怎么编译 Android 啊

请参考[README.md](https://github.com/zhouwg/kantv/blob/kantv/README.md)

**Comment by zhouwg** [comment]
> mac 编译 Android 不了 求全套编译好的

请参考[README.md](https://github.com/zhouwg/kantv/blob/kantv/README.md)从源代码构建出来

**Comment by 360060316** [comment]
大佬 有没有联系方式

**Comment by trial** [comment]
搭车求ios的IJKMediaFramework.framework,自行编译一直不过

**Comment by 360060316** [comment]
我ios能全套编译但是我不搞ios 用mac根本不能编译 Android，跑Ubuntu虚拟机只能编译arm64-v8a而且只能在Ubuntu编译app，真是要命

**Comment by 360060316** [comment]
> 搭车求ios的IJKMediaFramework.framework,自行编译一直不过



> 搭车求ios的IJKMediaFramework.framework,自行编译一直不过

我ios能全套编译但是我不搞ios 用mac根本不能编译 Android，跑Ubuntu虚拟机只能编译arm64-v8a而且只能在Ubuntu编译app，真是要命

**Comment by trial** [comment]
> > 搭车求ios的IJKMediaFramework.framework,自行编译一直不过
> 
> 我ios能全套编译但是我不搞ios 用mac根本不能编译 Android，跑Ubuntu虚拟机只能编译arm64-v8a而且只能在Ubuntu编译app，真是要命

大佬能把编译完的IJKMediaFramework.framework发我一份不

**Comment by 360060316** [comment]
> > > 搭车求ios的IJKMediaFramework.framework,自行编译一直不过
> > 
> > 
> > 我ios能全套编译但是我不搞ios 用mac根本不能编译 Android，跑Ubuntu虚拟机只能编译arm64-v8a而且只能在Ubuntu编译app，真是要命
> 
> 大佬能把编译完的IJKMediaFramework.framework发我一份不

我不搞ios删除了 开发工具几十g也删除

**Comment by zhouwg** [comment]
this project focus on Android-based device. so I will close this issue accordingly. Thank you for your understanding.
