### ISSUE TITLE
Undefined symbol: _CDRMC_FilterURL

### ISSUE THREAD

**Issue by trial** [zhouwg/kantv#57]
编译iOS framework时出错
ld: warning: -read_only_relocs cannot be used with arm64
Undefined symbols for architecture arm64:
  "_CDRMC_FilterURL", referenced from:
      _io_open_default in libavformat.a(options.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zhouwg** [comment]
pls comment the following line 

`url = CDRMC_FilterURL(url);`

in 

https://github.com/zhouwg/FFmpeg/blob/release/4.4/libavformat/options.c#L183
