### ISSUE TITLE
Build succeed but not run on iOS 

### ISSUE THREAD

**Issue by ProFive** [zhouwg/kantv#60]
all dependent ios native libs build finished, pls build IJKMediaDemo  via latest Xcode IDE    
    
   Open xcode then it show the errors: 
../kantv/ijkmedia/ijkplayer/ff_ffplay.c:92:10 'tensorflow/lite/c/c_api.h' file not found
../kantv/ijkmedia/ijkplayer/ff_ffplay.c:92:10 'tensorflow/lite/c/c_api.h' file not found

If I changed #define ENABLE_TENSORFLOW  0 then show more errors:

Undefined symbol: _CDRMC_FilterURL

Undefined symbol: _xmlCheckVersion

Undefined symbol: _xmlCleanupParser

Undefined symbol: _xmlCopyNode

Undefined symbol: _xmlDocGetRootElement

Undefined symbol: _xmlFirstElementChild

Undefined symbol: _xmlFree

Undefined symbol: _xmlFreeDoc

Undefined symbol: _xmlFreeNode

Undefined symbol: _xmlGetProp

Undefined symbol: _xmlNewNode

Undefined symbol: _xmlNextElementSibling

Undefined symbol: _xmlNodeGetContent

Undefined symbol: _xmlNodeSetContent

Undefined symbol: _xmlReadMemory

**Comment by zhouwg** [comment]
this project is focus on device side AI.
